### ISSUE TITLE
Bundle path change

### ISSUE THREAD

**Issue by jesuGMZ** [8p/EightPointsGuzzleBundle#136]
Docs says the path to add the bundle should be `EightPoints\Bundle\GuzzleBundle\EightPointsGuzzleBundle()` but using version 6.1 that bundle does not exists under that location but `EightPoints\Bundle\GuzzleBundle\GuzzleBundle`.

Thanks for this bundle :+1:

**Comment by gregurco** [comment]
@jesuGMZ you can see the correct path in correct readme:

- https://github.com/8p/EightPointsGuzzleBundle/blob/v6.1.0/README.md - version 6.1.0 and path is EightPoints\Bundle\GuzzleBundle\GuzzleBundle
- https://github.com/8p/EightPointsGuzzleBundle/blob/master/README.md - master and path is EightPoints\Bundle\GuzzleBundle\EightPointsGuzzleBundle
Notice that master !== 6.1.0 and the master will became version 7.0.0

Do I answer your question?

**Comment by jesuGMZ** [comment]
So far, by default composer will download the current stable 6.1.1 which does not match with the current doc in Packigst nor this repo what could be confused.

Close it if you consider it fine.

**Comment by florianpreusner** [comment]
I can understand that this is confusing. The README.md file downloaded by composer should always contain the right information. I think this is given, like @gregurco already written. It is only confusing because everybody is taking a look at the project github url. And in this case it contains information that doesn't match v6.x cause we are preparing v7.x. 

This will be solved automatically the day after tomorrow, Thursday, October 26th. Than I will release the new version.
