### ISSUE TITLE
[Logging] Logging large Requests fills memory

### ISSUE THREAD

**Issue by koenigsascha** [8p/EightPointsGuzzleBundle#255]
in `/src/Log/LogRequest.php`, Line 73:

`$this->setBody($request->getBody() ? $request->getBody()->__toString() : null);`

I tried POSTing a 250MB binary file and this line reads the whole file into a variable which results in "Fatal Error: Allowed memory size exhausted.". 

Disabling the logging in `eight_points_guzzle.yaml` with `logging: false` (like here: https://github.com/8p/EightPointsGuzzleBundle/blob/master/src/Resources/doc/configuration-reference.md) avoids the problem.

**Comment by gregurco** [comment]
Hello @koenigsascha 
Do you have any suggestions how to avoid this problem without disabling logger? I don't see another solution. If you know, that the response will be some large amount of information, then you disable logging and that's all, otherwise keep it as it is.

Finally, the logging is enabled by default only in dev mode. In prod this problem will not appear.

**Comment by koenigsascha** [comment]
In case it helps anyone:
The problem disappeared, after I did `apt install php-curl`

**Comment by gregurco** [comment]
@koenigsascha it's really strange, because guzzle can work without curl. You can check it here: https://github.com/guzzle/guzzle/blob/master/src/functions.php#L103
Otherwise `ext-curl` would be in `required` section in package.json, but it's only in dev dependency.
Finally it's great that this extension resolved your problem :+1: Thanks for info!
