### ISSUE TITLE
Clear up Event Subscriber and Event Listener in documentation

### ISSUE THREAD

**Issue by marcusorjames** [8p/EightPointsGuzzleBundle#279]
## The issue
I've noticed that in the documentation in the [code snippet ](https://github.com/8p/EightPointsGuzzleBundle/blob/master/src/Resources/doc/intercept-request-and-response.md#interceptor-class) the namespace is EventListener but in the [second snippet](https://github.com/8p/EightPointsGuzzleBundle/blob/master/src/Resources/doc/intercept-request-and-response.md#implement-interceptor-logic) and [third snippet](https://github.com/8p/EightPointsGuzzleBundle/blob/master/src/Resources/doc/intercept-request-and-response.md#intercept-response) it is EventSubscriber.
I think this is a mistake and this should be changed to EventListener. I came across this because I was looking to implement an EventSubscriber instead of a Listener but this isn't documented.

## Suggestions
* Change EventSubscriber in [second snippet](https://github.com/8p/EightPointsGuzzleBundle/blob/master/src/Resources/doc/intercept-request-and-response.md#implement-interceptor-logic) and [third snippet](https://github.com/8p/EightPointsGuzzleBundle/blob/master/src/Resources/doc/intercept-request-and-response.md#intercept-response) to EventListener
* Add EventSubscriber implementation example to documentation
```php
<?php
namespace App\EventSubscriber; 

use EightPoints\Bundle\GuzzleBundle\Events\GuzzleEvents;
use EightPoints\Bundle\GuzzleBundle\Events\PostTransactionEvent;
use Symfony\Component\EventDispatcher\EventSubscriberInterface;
use Symfony\Component\HttpFoundation\Response;

final class PartnersApiGuzzleSubscriber implements EventSubscriberInterface
{
    public static function getSubscribedEvents(): array
    {
        return [
            GuzzleEvents::POST_TRANSACTION => ['modifyResponse'],
        ];
    }

    public function modifyResponse(PostTransactionEvent $event): void
    {
        // get response from the event
        $response = $event->getTransaction();

        // check if response status code is 403
        if ($response->getStatusCode() === Response::HTTP_FORBIDDEN) {
            // invalidate token
        }
    }
```

There doesn't seem to be a specific interface for a Subscriber currently like the Listener, but this could be a start. I'm not too familiar with how subscribers work so not sure if you can do something similar with the service

**Comment by gregurco** [comment]
Good point, @marcusorjames 
Symfony has good article related to this topic: https://symfony.com/doc/current/event_dispatcher.html#listeners-or-subscribers
I also think that it's better to provide either listener or subscriber.

**Comment by rpkamp** [comment]
I think this is closed by #281

**Comment by gregurco** [comment]
@rpkamp yes and no :slightly_smiling_face: I did not add the case with Event Subscriber and I'm thinking do we need it or not.

**Comment by rpkamp** [comment]
Personally I'd keep it simple and just recommend the listener. It's easier to implement and easier to explain.

I would assume that people who want to create a subscriber are familiar enough with Symfony to write one for themselves.

Also, there is no clear way for Event Subscribers on how to filter on different clients like there is with event listeners.

**Comment by rpkamp** [comment]
Alternatively, two events could be fired for each request/response instead of one.

1. A generic event that fires regardless of which client is active, and
2. A client-specific event that can be handled by listeners/subscribers subscribing specifically to that client

The generic event can be used by listeners who want to do stuff like logging, tracing, profiling, auditing, etc.
The specific events can be used by listeners/subscribers that want to do something specific for a specific client (like auth headers etc).

Basically:

```php
$this->eventDispatcher->dispatch(
    GuzzleEvents::PRE_TRANSACTION,
    $preTransactionEvent
);
$this->eventDispatcher->dispatch(
    GuzzleEvents::PRE_TRANSACTION . '.' . $this->serviceName,
    $preTransactionEvent
);
```

So suppose I have a client called `payment` and a client called `crm`. I can:

1. Listen to `eight_points_guzzle.pre_transaction` to get _all_ events for both (and future) clients
1. Listen to `eight_points_guzzle.pre_transaction.payment` for all events from the `payment` client only
1. Listen to `eight_points_guzzle.pre_transaction.crm` for all events from the `crm` client only

This would have several advantages:

1. Listeners don't need to filter for the correct client anymore (`if ($event->getServiceName() !== $this->serviceName) { return; }`), they can subscribe to a specific client and not be bothered with events from other clients (which indeed means that `\EightPoints\Bundle\GuzzleBundle\Events\GuzzleEventListenerInterface` can be deprecated)
1. It's easy to implement subscribers because they can use the same events without needing any specific interfaces
1. Once `\EightPoints\Bundle\GuzzleBundle\Events\GuzzleEventListenerInterface` is removed, `\EightPoints\Bundle\GuzzleBundle\DependencyInjection\Compiler\EventHandlerCompilerPass` can be removed as well, as it doesn't serve a purpose anymore.

Thoughts? :slightly_smiling_face:

**Comment by gregurco** [comment]
@rpkamp I think it's good idea. Could you create separate issue with same text and we can discuss it there and probably plan some actions?

I close this issue.

**Comment by rpkamp** [comment]
Done https://github.com/8p/EightPointsGuzzleBundle/issues/283
