### ISSUE TITLE
Possibility to log request and response in separate logs

### ISSUE THREAD

**Issue by julien-maurel** [8p/EightPointsGuzzleBundle#303]
| Q                | A
| ---------------- | -----
| Symfony version  | 4.4
| Bundle version   | 8.1.0

Hi,
Perhaps it's already possible but I didn't find how : is it possible to logs request and response details in 2 separate logs?
Because when I activate logs on my client, I have only one logs after the response.
Thanks.

**Comment by gregurco** [comment]
Hello @julien-maurel 
Please check this PR: https://github.com/8p/EightPointsGuzzleBundle/pull/289
Does it solve your problem?

**Comment by julien-maurel** [comment]
Hi,
No, I tried this settings and I have only one log (after response) even if I set logging to REQUEST_AND_RESPONSE.
Waht I try is to have one log before request execution and one log after (with response).
Thanks

**Comment by gregurco** [comment]
Hello

Sorry for late response. If the problem is still actual then you can find the solution here:
1) create custom middleware similar with this one: https://github.com/8p/EightPointsGuzzleBundle/blob/master/src/Middleware/LogMiddleware.php
2) inject in middleware 2 loggers (not one, as in exemple)
3) Configure first logger to write in first log file and trigger this logger in request middleware section. In the response middleware section trigger the second logger, which should be configured to write to separate file.

Important to know here how to configure different symfony loggers and how guzzle middlewares work.
