### ISSUE TITLE
Headers: form_input post overrides given header "content-type"

### ISSUE THREAD

**Issue by florianpreusner** [8p/EightPointsGuzzleBundle#84]
As mentioned in #82, Guzzle overrides header "Content-Type" if option 'form_params' is given. 
This should be fixed, cause already existing content type headers should not be overridden.

https://github.com/guzzle/guzzle/blob/master/src/Client.php#L303
```php
private function applyOptions(RequestInterface $request, array &$options)
{
        ...
        if (isset($options['form_params'])) {
            ...
            $options['body'] = http_build_query($options['form_params'], '', '&');
            unset($options['form_params']);
            $options['_conditional']['Content-Type'] = 'application/x-www-form-urlencoded';
        }
        ...
```

**Comment by gregurco** [comment]
@florianpreusner I investigated this problem. So, we have 3 types of options:
- for client
- for request (conditional, by guzzle)
- for request (by user)
Finally they are merged. I wrote them in order of their priority. Ex: request options have higher priority than client's, evident. And rapplication/x-www-form-urlencoded;equest options provided by user have higher priority than request options from guzzle. What happens in case from #82:
1) you set header with charset for client
2) you do request with form_params
3) new *conditional* content type is set to request due to form_params
4) this conditional content type has bigger priority than content type from client

How to prevent this behavior? - simply to set content type to request and this one will have the biggest priority.

**Example with guzzle:**
```php
$client = new \GuzzleHttp\Client([
     'base_uri' => 'google.com',
     'headers' => ['Content-Type' => 'application/x-www-form-urlencoded; charset=utf-8']
]);

$client->request('GET', '', ['form_params'=> ['foo' => 'bar']]);
```
- real content type will be: *application/x-www-form-urlencoded;* - client options is replaced by conditional request option

**Comment by florianpreusner** [comment]
Thanks for investigation, @gregurco! I'm with you. By adding the possibility to override the header because of setting options in config we would change the normal behavior provided by guzzle. As you said, this could create issues in the future. A bundle should not change behavior, workflows or any other core functionality of a library! Going to close this issue.
